# Generated by Django 5.2.6 on 2025-10-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messmetapp', '0005_alter_user_full_name_alter_user_mobile_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hostel_status',
            field=models.CharField(choices=[('hosteller', 'Hosteller'), ('non_hosteller', 'Non-Hosteller')], default='non_hosteller', max_length=20),
        ),
    ]
