# Generated by Django 5.2.6 on 2025-10-22 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messmetapp', '0007_visitorfeedback_visitorpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='messmetapp.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='messmetapp.subscriptionplan'),
        ),
    ]
