# Generated by Django 5.2.6 on 2025-10-26 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messmetapp', '0009_foodimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('start_datetime', models.DateTimeField(help_text='When to start showing this notice')),
                ('end_datetime', models.DateTimeField(help_text='When to stop showing this notice')),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('hostellers', 'Hostellers Only'), ('non_hostellers', 'Non-Hostellers Only'), ('active_subscribers', 'Active Subscribers Only')], default='all', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily disable')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority notices show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Popup Notice',
                'verbose_name_plural': 'Popup Notices',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
